// Fill out your copyright notice in the Description page of Project Settings.


#include "GameManager.h"
#include "Components/AudioComponent.h"
#include "StatusWidget.h"
#include "RedZoneManager.h"
#include "Kismet/GameplayStatics.h" // Sets default values
#include "Blueprint/UserWidget.h"
#include "GameFramework/PlayerController.h"

AGameManager::AGameManager()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® ï¿½ï¿½ï¿½ï¿½
	AudioComponent = CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComponent"));
	AudioComponent->SetupAttachment(RootComponent);
	AudioComponent->bAutoActivate = false; // ï¿½Úµï¿½ ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½

#if WITH_EDITORONLY_DATA
	bIsSpatiallyLoaded = false; // ì›”ë“œ íŒŒí‹°ì…˜ì—ì„œ ê³µê°„ ì¶”ì  í•˜ì§€ ì•ŠìŒ
#endif

}

// Called when the game starts or when spawned
void AGameManager::BeginPlay()
{
	Super::BeginPlay();
	if (SoundToPlay1)
	{
		AudioComponent->SetSound(SoundToPlay1);
		AudioComponent->Play();
	}
}

// Called every frame
void AGameManager::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}


void AGameManager::lobby() //ï¿½Îºï¿½ ï¿½ï¿½ï¿½ï¿½
{
	//ï¿½Ã³×¸ï¿½Æ½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½


}

void AGameManager::Start() //ï¿½Êµï¿½ï¿½Ğ»ï¿½ ï¿½ï¿½ï¿½ï¿½
{
	if (SoundToPlay1)
	{
		AudioComponent->SetSound(SoundToPlay1);
		AudioComponent->Play();
		StatusWidget->changeUI();
	}
}

void AGameManager::middle() //ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
{
	if (SoundToPlay2)
	{
		AudioComponent->SetSound(SoundToPlay2);
		AudioComponent->Play();
		StatusWidget->changeUI();
	}
}

void AGameManager::end() //ï¿½Ú±ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
{
	if (SoundToPlay3)
	{
		AudioComponent->SetSound(SoundToPlay3);
		AudioComponent->Play();
		StatusWidget->changeUI();

		// RedZoneManager Ã£ï¿½ï¿½
		TArray<AActor*> FoundManagers;
		UGameplayStatics::GetAllActorsOfClass(GetWorld(), ARedZoneManager::StaticClass(), FoundManagers);

		if (FoundManagers.Num() > 0)
		{
			ARedZoneManager* redmanager = Cast<ARedZoneManager>(FoundManagers[0]);
			if (redmanager)
			{
				redmanager->StartRedZone();
			}
		}
	}
}

void AGameManager::SetBGM(bool play)
{
	AudioComponent->SetPaused(play);
}

void AGameManager::win() //ìŠ¹ë¦¬
{
	/*if (VictoryWidgetClass)
	{
		APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
		if (PC)
		{
			VictoryWidgetInstance = CreateWidget<UUserWidget>(PC, VictoryWidgetClass);
			if (VictoryWidgetInstance)
			{
				VictoryWidgetInstance->AddToViewport();

				FInputModeUIOnly InputMode;
				InputMode.SetWidgetToFocus(VictoryWidgetInstance->TakeWidget());
				InputMode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);
				PC->SetInputMode(InputMode);
				PC->bShowMouseCursor = true;
			}
		}
	}*/



	/*UE_LOG(LogTemp, Warning, TEXT("ğŸ† GameManager::win() í•¨ìˆ˜ í˜¸ì¶œë¨."));

	if (VictoryWidgetClass)
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ† VictoryWidgetClass ìœ íš¨í•¨."));

		APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
		if (PC)
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ† PlayerController ì°¾ìŒ. ìœ„ì ¯ ìƒì„± ì‹œë„."));

			VictoryWidgetInstance = CreateWidget<UUserWidget>(PC, VictoryWidgetClass);
			if (VictoryWidgetInstance)
			{
				UE_LOG(LogTemp, Warning, TEXT("ğŸ† Victory ìœ„ì ¯ ìƒì„± ì„±ê³µ. í™”ë©´ì— ì¶”ê°€í•©ë‹ˆë‹¤."));

				VictoryWidgetInstance->AddToViewport();

				FInputModeUIOnly InputMode;
				InputMode.SetWidgetToFocus(VictoryWidgetInstance->TakeWidget());
				InputMode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);
				PC->SetInputMode(InputMode);
				PC->bShowMouseCursor = true;
			}
			else
			{
				UE_LOG(LogTemp, Error, TEXT("â›” Victory ìœ„ì ¯ ìƒì„± ì‹¤íŒ¨."));
			}
		}
		else
		{
			UE_LOG(LogTemp, Error, TEXT("â›” PlayerController ì°¾ê¸° ì‹¤íŒ¨."));
		}
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("â›” VictoryWidgetClassê°€ ì„¤ì •ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤."));
	}*/
}
